### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by petrakuk** [mikeant42/PureSearch#1]
Hi,
I try but I can't get login and password to control panel. Any suggestions ?
Thanks

**Comment by mikeant42** [comment]
Here's the sql file to create the database `searchusers`.

```
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

--
-- Database: `purity`
--

-- --------------------------------------------------------

--
-- Table structure for table `searchusers`
--

CREATE TABLE `searchusers` (
  `username` varchar(90) NOT NULL,
  `password` varchar(90) NOT NULL,
  `id` int(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=3 ;
```

And the `colleges` database:

```
--
-- Database: `purity`
--

-- --------------------------------------------------------

--
-- Table structure for table `colleges`
--

CREATE TABLE `colleges` (
  `name` mediumtext COLLATE latin1_general_ci NOT NULL,
  `description` longtext COLLATE latin1_general_ci NOT NULL,
  `link` mediumtext COLLATE latin1_general_ci NOT NULL,
  FULLTEXT KEY `description` (`description`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1 COLLATE=latin1_general_ci;
```

Afterwards, just manually enter your username and hashed password into the `searchusers` table.

To hash the password use `echo bcrypt_password("Yourpassword");` (from login.php) and then use that as the password in the database.

As a side note, this project is old and hasn't been extensively tested, so expect errors. Keep in mind that this is a project that was mostly a learning experience more than anything else, so much of the ui is quite outdated.

**Comment by petrakuk** [comment]
Great, thanks
